import { NextResponse } from 'next/server'

// Step definitions loaded statically
// These will be populated by the data extraction agent
const STEP_DEFINITIONS = [
  // Phase 0: Fundação
  { key: 'p0_s1', phase: 0, order: 1, title: 'Definir Nicho e Expert', description: 'Escolher o nicho validado e definir o expert que vai entregar o evento', howTo: 'Analisar os 15 nichos validados, verificar se o expert tem autoridade no assunto, avaliar audiência existente', benchmark: 'Expert com pelo menos alguma presença online; cases com 3k seguidores já funcionam', tip: 'Não precisa de audiência grande. Com tráfego pago, 3.000 seguidores são suficientes para vender 500+ ingressos', commonError: 'Escolher nicho muito amplo. Quanto mais específico, melhor a conversão', items: ['Nicho definido e validado', 'Expert confirmado', 'Proposta de valor clara'] },
  { key: 'p0_s2', phase: 0, order: 2, title: 'Definir Big Idea e Narrativa', description: 'Criar o conceito central do evento e a história que vai guiar toda comunicação', howTo: 'Identificar a transformação principal, criar uma promessa específica e diferenciada', benchmark: 'Big Idea deve ser resumida em 1 frase de impacto', tip: 'A Big Idea precisa ser algo que o público não encontra em lugar nenhum. É o que diferencia seu evento de qualquer outro conteúdo gratuito', commonError: 'Big Idea genérica tipo "aprenda marketing digital". Precisa ser específica e única', items: ['Big Idea definida', 'Narrativa criada', 'Tema do evento definido', 'Promessa principal clara'] },
  { key: 'p0_s3', phase: 0, order: 3, title: 'Estruturar Oferta e Produto', description: 'Montar a oferta completa: ingresso + order bumps + high ticket + downsell', howTo: 'Definir produto principal (high ticket), precificar ingresso, criar order bumps com cashback, definir downsell', benchmark: 'Ingresso R$47-497, High Ticket R$997-12.000, Order Bump de gravações com conversão 4-6.5%', tip: 'Use "acesso em formato de aulas" ao invés de "replay" — conversão vai de 1.1% para 6.5%+', commonError: 'Chamar gravações de "replay". Isso mata a conversão', items: ['Produto principal definido e precificado', 'Ingressos precificados', 'Order bumps criados', 'Cashback configurado', 'Downsell definido', 'Tripwire definido (opcional)'] },
  { key: 'p0_s4', phase: 0, order: 4, title: 'Criar Estratégia de Lotes', description: 'Definir 7-9 lotes com escassez progressiva', howTo: 'Criar lotes com incremento de ~15% no preço. Primeiro lote menor (escassez). Lote 0 para lançamento com base', benchmark: '7-9 lotes, primeiro lote ~50% menor que os demais, incremento de 15% entre lotes', tip: 'Lote 0 (pré-venda para base) converte até 40% quando já tem audiência', commonError: 'Poucos lotes (3-4). Precisa de pelo menos 7 para criar urgência constante', items: ['Lotes definidos (7-9)', 'Preços progressivos', 'Quantidades por lote', 'Datas de virada planejadas'] },
  { key: 'p0_s5', phase: 0, order: 5, title: 'Definir Meta e Orçamento', description: 'Calcular meta de ingressos, orçamento, CPA máximo e pacing', howTo: 'Definir meta de ingressos → calcular orçamento necessário → CPA máximo = orçamento/ingressos_tráfego → pacing = meta/dias', benchmark: 'CPA início R$15-28, meio R$40-50. ROAS meta 5x+', tip: 'Reserve 82% do orçamento para vendas diretas, 10% conteúdo, 5% remarketing, 3% reserva', commonError: 'Não calcular CPA máximo antes de começar. Sem esse número, não tem como avaliar performance', items: ['Meta de ingressos definida', 'Orçamento total aprovado', 'CPA máximo calculado', 'Pacing diário definido', 'Alocação de orçamento planejada'] },
  { key: 'p0_s6', phase: 0, order: 6, title: 'Montar Equipe e Responsáveis', description: 'Definir funções: estrategista, tráfego, copy, design, automações, comercial', howTo: 'Mapear todas as funções necessárias e designar responsáveis. Mínimo: estrategista + tráfego + copy', benchmark: 'Equipe mínima: 3 pessoas. Ideal: 5-7 com comercial dedicado', tip: 'Time comercial com script de cashback aumenta vendas do high ticket em até 35%', commonError: 'Não ter time comercial. O comercial é responsável por uma parte significativa das vendas do high ticket', items: ['Estrategista definido', 'Gestor de tráfego definido', 'Copywriter definido', 'Designer definido', 'Time comercial montado', 'Funções e responsabilidades claras'] },

  // Phase 1: Pré-Lançamento
  { key: 'p1_s1', phase: 1, order: 1, title: 'Criar Página de Vendas', description: 'Landing page otimizada com copy persuasiva, lotes e checkout', howTo: 'Usar framework: Hook → Problema → Mecanismo → Prova → Oferta → Escassez → CTA', benchmark: 'Taxa de conversão da página: 6-9% (bom). Checkout to compra: 40-48%', tip: 'Página simples converte mais. Não precisa de vídeo longo. Copy direta com escassez real', commonError: 'Página muito longa sem escassez. Ou checkout com muitos passos (ideal: 1-2 passos)', items: ['Página de vendas publicada', 'Copy revisada (sem "aprenda", sem "replay")', 'Lotes configurados', 'Checkout funcionando', 'Pixel instalado', 'UTMs configuradas'] },
  { key: 'p1_s2', phase: 1, order: 2, title: 'Configurar Automações', description: 'Email, WhatsApp, checkout, gateway de pagamento, grupos', howTo: 'Configurar gateway, setup de emails automáticos (confirmação, lembretes), grupo de WhatsApp com mensagem de boas-vindas', benchmark: 'Email de confirmação em < 5 minutos. WhatsApp: mensagem automática na compra', tip: 'Grupo de WhatsApp é onde a mágica acontece. Lembrete do evento + pitch comercial', commonError: 'Não configurar automações antes de ligar o tráfego. Leads compram e não recebem nada', items: ['Gateway configurado', 'Emails automáticos ativos', 'Grupo WhatsApp criado', 'Bot de WhatsApp configurado', 'Página de obrigado pronta', 'Recuperação de boleto ativa'] },
  { key: 'p1_s3', phase: 1, order: 3, title: 'Criar Criativos', description: 'Produzir criativos para tráfego pago: UGC, vídeo expert, estáticos', howTo: 'Mínimo 10 criativos. Mix: 5 UGC + 3 vídeo expert + 2 estáticos. Framework: Hook 3s → Problema → Solução → CTA', benchmark: 'CTR bom: >1%. Muito bom: >1.5%. Ter pelo menos 3-5 criativos campeões', tip: 'UGC costuma performar melhor que vídeo profissional. Autenticidade > produção', commonError: 'Poucos criativos (2-3). Precisa de volume para testar e encontrar os campeões', items: ['10+ criativos produzidos', 'Mix de formatos (UGC, expert, estático)', 'Copies das legendas prontas', 'Aprovação do expert', 'Variações de hook testáveis'] },
  { key: 'p1_s4', phase: 1, order: 4, title: 'Configurar Campanhas de Tráfego', description: 'Setup das campanhas no Facebook/Google com estrutura otimizada', howTo: 'Facebook: Advantage+ (single shot) ou CBO. Google: Search + YouTube. Estrutura: 75-82% Facebook, 10-12% Google', benchmark: 'CPM referência: R$16-28. CPC bom: <R$2. CTR meta: >1%', tip: 'Advantage+ Shopping Campaign (single shot) simplifica e performa bem. Não precisa de segmentação manual', commonError: 'Segmentação muito restrita. Deixe o algoritmo trabalhar, especialmente no Advantage+', items: ['Conta de anúncios configurada', 'Pixel e conversões configurados', 'Campanhas criadas', 'Orçamento alocado (82% vendas)', 'Criativos carregados', 'UTMs em todos os links'] },
  { key: 'p1_s5', phase: 1, order: 5, title: 'Preparar Conteúdo Orgânico', description: 'Planejar posts, stories, reels para período de vendas', howTo: 'Criar calendário de 15-20 dias de conteúdo. Mix: 40% valor, 30% prova social, 20% oferta, 10% bastidores', benchmark: 'Orgânico deve representar ~13% das vendas totais', tip: 'Conteúdo que vende: resolva 1 problema real do seu público em cada post. Não venda diretamente, gere desejo', commonError: 'Só postar sobre o evento. Precisa mixar com conteúdo de valor que gera desejo', items: ['Calendário de conteúdo criado', 'Posts programados', 'Stories planejados', 'Reels gravados', 'Prova social coletada'] },
  { key: 'p1_s6', phase: 1, order: 6, title: 'Testar Toda a Jornada', description: 'Compra teste end-to-end: página → checkout → email → WhatsApp → grupo', howTo: 'Fazer compra teste com cartão real. Verificar todo fluxo até receber no grupo', benchmark: 'Jornada completa em < 5 minutos. Zero erros no fluxo', tip: 'Faça pelo menos 3 compras teste com emails diferentes. Teste em mobile e desktop', commonError: 'Não testar antes de ligar o tráfego. Primeiro dia de tráfego com checkout quebrado', items: ['Compra teste realizada', 'Email recebido', 'WhatsApp recebido', 'Entrada no grupo ok', 'Fluxo mobile testado', 'Zero erros encontrados'] },

  // Phase 2: Lançamento (Vendas)
  { key: 'p2_s1', phase: 2, order: 1, title: 'Ativar Tráfego Pago', description: 'Ligar campanhas e monitorar primeiras 24-48h', howTo: 'Ativar campanhas, monitorar CPA nas primeiras 24h, ajustar se necessário', benchmark: 'Primeiras vendas em < 6h. CPA inicial: R$15-28', tip: 'Não mexa nas campanhas nas primeiras 48h. Deixe o algoritmo otimizar', commonError: 'Pausar campanha com CPA alto nas primeiras horas. Precisa de pelo menos 48h de dados', items: ['Campanhas ativadas', 'CPA monitorado', 'Primeiras vendas confirmadas', 'Dashboard de métricas ativo'] },
  { key: 'p2_s2', phase: 2, order: 2, title: 'Gestão Diária de Tráfego', description: 'Otimizar campanhas, pausar criativos ruins, escalar bons', howTo: 'Checklist diário: verificar CPA por criativo, pausar CPA > 2x máximo, escalar criativos com CPA < máximo', benchmark: 'CPA deve ficar abaixo do máximo calculado. CTR > 1%', tip: 'Se CPA subir acima do máximo por 2+ dias consecutivos, pause os criativos ruins e suba novos', commonError: 'Não olhar métricas diariamente. Ou olhar só gasto sem ver CPA e CTR', items: ['Métricas diárias acompanhadas', 'Criativos ruins pausados', 'Criativos bons escalados', 'Orçamento otimizado'] },
  { key: 'p2_s3', phase: 2, order: 3, title: 'Viradas de Lote', description: 'Executar viradas de lote com comunicação de urgência', howTo: 'Avisar 24h antes da virada. No dia: email + WhatsApp + stories + ads com urgência', benchmark: 'Picos de venda nas viradas de lote. Lotes devem esgotar conforme planejado', tip: 'A virada de lote é o momento de maior conversão. Dedique esforço extra de comunicação', commonError: 'Não comunicar a virada com antecedência. O público precisa saber que o preço vai subir', items: ['Avisos de virada enviados (24h antes)', 'Comunicação de urgência ativa', 'Novo lote ativado', 'Preço atualizado na página'] },
  { key: 'p2_s4', phase: 2, order: 4, title: 'Comunicação Diária Multi-canal', description: 'Manter ritmo de comunicação: email, WhatsApp, Instagram, ads', howTo: 'Seguir calendário de 44 dias. Cada dia tem ações específicas por canal', benchmark: '1-2 emails por semana, stories diários, WhatsApp 2-3x por semana', tip: 'Não tenha medo de comunicar. Quem comprou quer receber informações sobre o evento', commonError: 'Parar de comunicar depois das primeiras vendas. Comunicação constante = vendas constantes', items: ['Emails programados', 'Stories diários', 'WhatsApp no grupo', 'Conteúdo orgânico postado'] },
  { key: 'p2_s5', phase: 2, order: 5, title: 'Monitorar Pacing', description: 'Verificar se vendas estão no ritmo da meta diária', howTo: 'Comparar vendas reais vs pacing ideal. Se 20% abaixo, escalar tráfego ou criar promoção', benchmark: 'Pacing = meta / dias de venda. Variação aceitável: ±20%', tip: 'Se o pacing estiver abaixo, considere: 1) Mais orçamento 2) Novos criativos 3) Lote especial', commonError: 'Ignorar pacing baixo nos primeiros dias achando que vai recuperar depois', items: ['Pacing verificado diariamente', 'Ajustes realizados se necessário'] },

  // Phase 3: Evento
  { key: 'p3_s1', phase: 3, order: 1, title: 'Preparar Evento', description: 'Setup técnico, roteiro, equipe, links', howTo: 'Testar plataforma, preparar roteiro com momentos de pitch, configurar links de compra', benchmark: 'Evento mínimo 3h. Plataforma testada 24h antes. Comparecimento meta: 65-80%', tip: 'Evento começa às 16h no mínimo. Nunca antes. Sábado é o melhor dia', commonError: 'Evento muito curto (<2h) ou sem roteiro claro. Precisa de estrutura: conteúdo → pitch → Q&A', items: ['Plataforma testada', 'Roteiro finalizado', 'Links de compra prontos', 'Equipe briefada', 'Lembretes programados (D-7, D-1, D0)'] },
  { key: 'p3_s2', phase: 3, order: 2, title: 'Executar Evento', description: 'Realizar o evento com pitch estruturado', howTo: 'Abrir com impacto, entregar conteúdo de valor, fazer pitch com oferta + escassez + cashback', benchmark: 'Presença: 55-80%. Conversão high ticket: 15-33% dos presentes', tip: 'O pitch não é no final. Intercale conteúdo com micro-pitches ao longo do evento', commonError: 'Deixar pitch só para o final quando metade já saiu. Integre a oferta ao conteúdo', items: ['Evento realizado', 'Pitch executado', 'Links compartilhados', 'Vendas durante evento monitoradas', 'Ofertas especiais do evento ativadas'] },
  { key: 'p3_s3', phase: 3, order: 3, title: 'Ativar Time Comercial', description: 'Time comercial faz abordagem ativa pós-evento', howTo: 'Comercial aborda leads no WhatsApp com script de cashback. Foco: quem comprou gravações', benchmark: 'Conversão comercial: 30-55% dos leads abordados (se qualificados)', tip: 'O script de cashback é o mais poderoso: "Você já pagou R$197 nas gravações, esse valor vira desconto no produto"', commonError: 'Não ter time comercial ou time sem script. Abordagem sem roteiro converte muito menos', items: ['Scripts distribuídos para o time', 'Leads qualificados listados', 'Abordagens iniciadas', 'Pipeline de follow-up ativo'] },

  // Phase 4: Pós-Evento
  { key: 'p4_s1', phase: 4, order: 1, title: 'Abertura de Carrinho', description: 'Abrir vendas do high ticket para quem participou do evento', howTo: 'Enviar email + WhatsApp com oferta do high ticket. Mínimo 3 dias de carrinho aberto', benchmark: 'Conversão nos primeiros 3 dias após evento: 60-70% das vendas totais do high ticket', tip: 'Carrinho deve ficar aberto no MÍNIMO 3 dias. Menos que isso perde muita venda', commonError: 'Fechar carrinho no mesmo dia do evento. Muita gente precisa de 2-3 dias para decidir', items: ['Carrinho aberto', 'Email de abertura enviado', 'WhatsApp de abertura enviado', 'Oferta especial ativa (se houver)'] },
  { key: 'p4_s2', phase: 4, order: 2, title: 'Follow-up Estruturado', description: 'Sequência de follow-up: D+1, D+3, D+5, D+7', howTo: 'Enviar comunicações em ritmo decrescente. D+1: urgência. D+3: prova social. D+5: última chance', benchmark: '40-60% das vendas do high ticket acontecem no follow-up pós-evento', tip: 'Cada follow-up deve ter um ângulo diferente: urgência, prova social, escassez, bônus exclusivo', commonError: 'Mandar a mesma mensagem repetida. Cada follow-up precisa de um gancho diferente', items: ['Follow-up D+1 enviado', 'Follow-up D+3 enviado', 'Follow-up D+5 enviado', 'Downsell oferecido para quem não comprou'] },
  { key: 'p4_s3', phase: 4, order: 3, title: 'Downsell', description: 'Oferecer alternativa mais acessível para quem não comprou', howTo: 'Após encerramento do high ticket, oferecer versão mais barata para não-compradores', benchmark: 'Conversão de downsell: 5-15% dos não-compradores', tip: 'O downsell não é o produto principal com desconto. É uma versão diferente, mais enxuta', commonError: 'Oferecer downsell antes de encerrar o high ticket. O downsell é sempre DEPOIS', items: ['Downsell configurado', 'Comunicação de downsell enviada', 'Prazo limitado definido'] },
  { key: 'p4_s4', phase: 4, order: 4, title: 'Encerramento e Análise', description: 'Fechar carrinho, analisar métricas, documentar aprendizados', howTo: 'Encerrar vendas, compilar métricas finais, calcular ROAS real, documentar o que funcionou', benchmark: 'ROAS final meta: 5x+. Documentar para próximo lançamento', tip: 'Documente TUDO: o que funcionou, o que não funcionou, criativos campeões, melhores dias de venda', commonError: 'Não documentar. Cada lançamento deve alimentar o próximo com dados reais', items: ['Carrinho encerrado', 'Métricas finais compiladas', 'ROAS calculado', 'Relatório criado', 'Aprendizados documentados', 'Planejamento do próximo lançamento'] },
]

export async function GET() {
  return NextResponse.json(STEP_DEFINITIONS)
}
